# Generated by Django 4.1.3 on 2023-07-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Order',
        ),
    ]
