# Generated by Django 4.1.3 on 2023-07-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
