# Generated by Django 4.1.3 on 2023-07-26 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date',
            field=models.DateField(default=datetime.datetime.today, null=True),
        ),
    ]
