# Generated by Django 4.1.3 on 2023-07-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_orderitem_date_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('dispatch', 'DISPATCH'), ('on the way', 'ON THE WAY'), ('delivered', 'DELIVERED'), ('cancel', 'CANCEL'), ('return', 'RETURN')], default=None, max_length=150, null=True),
        ),
    ]
