# Generated by Django 4.1.3 on 2023-07-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('dispatch', 'DISPATCH'), ('on the way', 'ON THE WAY'), ('delivered', 'DELIVERED'), ('cancel', 'CANCEL'), ('return', 'RETURN')], default=None, max_length=150, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.productstatus'),
        ),
    ]
