# Generated by Django 4.1.3 on 2023-07-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_productstatus_remove_product_status_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
