# Generated by Django 4.1.3 on 2023-07-31 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_festivaldiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festivaldiscount',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='festivaldiscount',
            name='end_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='festivaldiscount',
            name='start_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
