# Generated by Django 4.1.3 on 2023-08-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_coupon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
