# Generated by Django 4.1.3 on 2023-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_orderitem_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.IntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_amount',
            field=models.IntegerField(default=500, null=True),
        ),
    ]
