# Generated by Django 4.1.3 on 2023-08-29 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='colorcode',
        ),
    ]
